// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createArgument = `-- name: CreateArgument :one
INSERT INTO argument (
  id,
  creation_date,
  last_update_time,
  brief,
  description
)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
) RETURNING id, creation_date, last_update_time, brief, description
`

type CreateArgumentParams struct {
	Brief       string
	Description sql.NullString
}

func (q *Queries) CreateArgument(ctx context.Context, arg CreateArgumentParams) (Argument, error) {
	row := q.db.QueryRowContext(ctx, createArgument, arg.Brief, arg.Description)
	var i Argument
	err := row.Scan(
		&i.ID,
		&i.CreationDate,
		&i.LastUpdateTime,
		&i.Brief,
		&i.Description,
	)
	return i, err
}

const createArgumentSources = `-- name: CreateArgumentSources :one
INSERT INTO argumentSources (
  id,
  creation_date,
  last_update_time,
  content,
  argument_id
)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
)
RETURNING id, creation_date, last_update_time, content, argument_id
`

type CreateArgumentSourcesParams struct {
	Content    string
	ArgumentID uuid.UUID
}

func (q *Queries) CreateArgumentSources(ctx context.Context, arg CreateArgumentSourcesParams) (Argumentsource, error) {
	row := q.db.QueryRowContext(ctx, createArgumentSources, arg.Content, arg.ArgumentID)
	var i Argumentsource
	err := row.Scan(
		&i.ID,
		&i.CreationDate,
		&i.LastUpdateTime,
		&i.Content,
		&i.ArgumentID,
	)
	return i, err
}

const createThesis = `-- name: CreateThesis :one
INSERT INTO thesis (
  id,
  creation_date,
  last_update_time,
  title,
  description
) VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
) RETURNING id, creation_date, last_update_time, title, description
`

type CreateThesisParams struct {
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateThesis(ctx context.Context, arg CreateThesisParams) (Thesis, error) {
	row := q.db.QueryRowContext(ctx, createThesis, arg.Title, arg.Description)
	var i Thesis
	err := row.Scan(
		&i.ID,
		&i.CreationDate,
		&i.LastUpdateTime,
		&i.Title,
		&i.Description,
	)
	return i, err
}
