// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_thesis_argument.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertTheisJoinArgument = `-- name: InsertTheisJoinArgument :exec
INSERT INTO thesis_argument (
  thesis_id,
  argument_id
)
VALUES (
  $1,
  $2
)
`

type InsertTheisJoinArgumentParams struct {
	ThesisID   uuid.UUID
	ArgumentID uuid.UUID
}

func (q *Queries) InsertTheisJoinArgument(ctx context.Context, arg InsertTheisJoinArgumentParams) error {
	_, err := q.db.ExecContext(ctx, insertTheisJoinArgument, arg.ThesisID, arg.ArgumentID)
	return err
}
