// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Argument struct {
	ID             uuid.UUID
	CreationDate   time.Time
	LastUpdateTime time.Time
	Brief          string
	Description    sql.NullString
}

type Thesis struct {
	ID             uuid.UUID
	CreationDate   time.Time
	LastUpdateTime time.Time
	Title          string
	Description    sql.NullString
}
