// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Thesis struct {
	ID             uuid.UUID
	CreationDate   time.Time
	LastUpdateTime time.Time
	Title          string
}
