// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getThesisById = `-- name: GetThesisById :many
SELECT
  id,
  creation_date,
  last_update_time,
  title,
  description
FROM thesis
WHERE id = ANY($1::UUID[])
`

func (q *Queries) GetThesisById(ctx context.Context, dollar_1 []uuid.UUID) ([]Thesis, error) {
	rows, err := q.db.QueryContext(ctx, getThesisById, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thesis
	for rows.Next() {
		var i Thesis
		if err := rows.Scan(
			&i.ID,
			&i.CreationDate,
			&i.LastUpdateTime,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
