// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: select.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getArgumentFromThesisId = `-- name: GetArgumentFromThesisId :many
SELECT
  argument.id,
  argument.creation_date,
  argument.last_update_time,
  argument.brief,
  argument.description
FROM argument
JOIN thesis_argument
  ON argument.id = thesis_argument.argument_id
WHERE thesis_argument.thesis_id = $1
`

func (q *Queries) GetArgumentFromThesisId(ctx context.Context, thesisID uuid.UUID) ([]Argument, error) {
	rows, err := q.db.QueryContext(ctx, getArgumentFromThesisId, thesisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Argument
	for rows.Next() {
		var i Argument
		if err := rows.Scan(
			&i.ID,
			&i.CreationDate,
			&i.LastUpdateTime,
			&i.Brief,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSourceFromArgumentId = `-- name: GetSourceFromArgumentId :many
SELECT
  id,
  creation_date,
  last_update_time,
  content,
  argument_id
FROM argumentSources
WHERE argument_id = $1
`

func (q *Queries) GetSourceFromArgumentId(ctx context.Context, argumentID uuid.UUID) ([]Argumentsource, error) {
	rows, err := q.db.QueryContext(ctx, getSourceFromArgumentId, argumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Argumentsource
	for rows.Next() {
		var i Argumentsource
		if err := rows.Scan(
			&i.ID,
			&i.CreationDate,
			&i.LastUpdateTime,
			&i.Content,
			&i.ArgumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThesisById = `-- name: GetThesisById :many
SELECT
  id,
  creation_date,
  last_update_time,
  title,
  description
FROM thesis
WHERE id = ANY($1::UUID[])
`

func (q *Queries) GetThesisById(ctx context.Context, dollar_1 []uuid.UUID) ([]Thesis, error) {
	rows, err := q.db.QueryContext(ctx, getThesisById, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thesis
	for rows.Next() {
		var i Thesis
		if err := rows.Scan(
			&i.ID,
			&i.CreationDate,
			&i.LastUpdateTime,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
